require 'osx/objc/oc_all'

module OSX

  ns_import :NSObject
  ns_import :NSActionCell
  ns_import :NSAffineTransform
  ns_import :NSAppleScript
  ns_import :NSApplication
  ns_import :NSAttributedString
  ns_import :NSMutableAttributedString
  ns_import :NSBezierPath
  ns_import :NSBitmapImageRep
  ns_import :NSBox
  ns_import :NSBrowser
  ns_import :NSBrowserCell
  ns_import :NSButton
  ns_import :NSButtonCell
  ns_import :NSCachedImageRep
  ns_import :NSCell
  ns_import :NSClipView
  ns_import :NSView
  ns_import :NSColor
  ns_import :NSCoder
  ns_import :NSColorList
  ns_import :NSColorPanel
  ns_import :NSColorPicker
  ns_import :NSColorWell
  ns_import :NSComboBox
  ns_import :NSComboBoxCell
  ns_import :NSControl
  ns_import :NSCursor
  ns_import :NSCustomImageRep
  ns_import :NSDocument
  ns_import :NSDocumentController
  ns_import :NSDrawer
  ns_import :NSWindow
  ns_import :NSEPSImageRep
  ns_import :NSEvent
  ns_import :NSFileWrapper
  ns_import :NSFont
  ns_import :NSFontManager
  ns_import :NSFontPanel
  ns_import :NSForm
  ns_import :NSFormCell
  ns_import :NSGlyphInfo
  ns_import :NSGraphicsContext
  ns_import :NSHelpManager
  ns_import :NSBundle
  ns_import :NSImage
  ns_import :NSImageCell
  ns_import :NSImageRep
  ns_import :NSImageView
  ns_import :NSInputManager
  ns_import :NSInputServer
  ns_import :NSResponder
  ns_import :NSLayoutManager
  ns_import :NSMatrix
  ns_import :NSMenu
  ns_import :NSMenuItem
  ns_import :NSMenuItemCell
  ns_import :NSMenuView
  ns_import :NSMovie
  ns_import :NSMovieView
  ns_import :NSNibConnector
  ns_import :NSNibControlConnector
  ns_import :NSNibOutletConnector
  ns_import :NSOpenGLPixelFormat
  ns_import :NSOpenGLContext
  ns_import :NSOpenGLView
  ns_import :NSOpenPanel
  ns_import :NSOutlineView
  ns_import :NSPageLayout
  ns_import :NSPanel
  ns_import :NSTextTab
  ns_import :NSParagraphStyle
  ns_import :NSMutableParagraphStyle
  ns_import :NSPasteboard
  ns_import :NSURL
  ns_import :NSPDFImageRep
  ns_import :NSPICTImageRep
  ns_import :NSPopUpButton
  ns_import :NSPopUpButtonCell
  ns_import :NSPrinter
  ns_import :NSPrintInfo
  ns_import :NSPrintOperation
  ns_import :NSPrintPanel
  ns_import :NSProgressIndicator
  ns_import :NSQuickDrawView
  ns_import :NSRulerMarker
  ns_import :NSRulerView
  ns_import :NSSavePanel
  ns_import :NSScreen
  ns_import :NSScroller
  ns_import :NSScrollView
  ns_import :NSSecureTextField
  ns_import :NSSecureTextFieldCell
  ns_import :NSSlider
  ns_import :NSSliderCell
  ns_import :NSSound
  ns_import :NSSpellChecker
  ns_import :NSSplitView
  ns_import :NSStatusBar
  ns_import :NSStatusItem
  ns_import :NSStepper
  ns_import :NSStepperCell
  ns_import :NSString
  ns_import :NSTableColumn
  ns_import :NSTableHeaderCell
  ns_import :NSTableHeaderView
  ns_import :NSTableView
  ns_import :NSTabView
  ns_import :NSTabViewItem
  ns_import :NSText
  ns_import :NSTextAttachmentCell
  ns_import :NSTextAttachment
  ns_import :NSTextContainer
  ns_import :NSTextField
  ns_import :NSTextFieldCell
  ns_import :NSTextStorage
  ns_import :NSTextView
  ns_import :NSToolbar
  ns_import :NSToolbarItem
  ns_import :NSTypesetter
  ns_import :NSSimpleHorizontalTypesetter
  ns_import :NSWindowController
  ns_import :NSWorkspace

end
