require 'osx/objc/oc_all'

module OSX

  ns_import :NSAppleEventDescriptor
  ns_import :NSAppleEventManager
  ns_import :NSAppleScript
  ns_import :NSArchiver
  ns_import :NSUnarchiver
  ns_import :NSObject
  ns_import :NSArray
  ns_import :NSMutableArray
  ns_import :NSAttributedString
  ns_import :NSMutableAttributedString
  ns_import :NSAutoreleasePool
  ns_import :NSBundle
  ns_import :NSCalendarDate
  ns_import :NSDate
  ns_import :NSCharacterSet
  ns_import :NSMutableCharacterSet
  ns_import :NSClassDescription
  ns_import :NSCoder
  ns_import :NSConnection
  ns_import :NSDistantObjectRequest
  ns_import :NSData
  ns_import :NSMutableData
  ns_import :NSDateFormatter
  ns_import :NSDecimalNumber
  ns_import :NSDecimalNumberHandler
  ns_import :NSNumber
  ns_import :NSScanner
  ns_import :NSDictionary
  ns_import :NSMutableDictionary
  ns_import :NSDistantObject
  ns_import :NSDistributedLock
  ns_import :NSDistributedNotificationCenter
  ns_import :NSEnumerator
  ns_import :NSException
  ns_import :NSAssertionHandler
  ns_import :NSFileHandle
  ns_import :NSPipe
  ns_import :NSFileManager
  ns_import :NSDirectoryEnumerator
  ns_import :NSFormatter
  ns_import :NSValue
  ns_import :NSHost
  ns_import :NSInvocation
  ns_import :NSKeyedArchiver
  ns_import :NSKeyedUnarchiver
  ns_import :NSLock
  ns_import :NSConditionLock
  ns_import :NSRecursiveLock
  ns_import :NSMethodSignature
  ns_import :NSNetService
  ns_import :NSNetServiceBrowser
  ns_import :NSNotification
  ns_import :NSNotificationCenter
  ns_import :NSNotificationQueue
  ns_import :NSNull
  ns_import :NSNumberFormatter
  ns_import :NSString
  ns_import :NSPort
  ns_import :NSMachPort
  ns_import :NSMessagePort
  ns_import :NSSocketPort
  ns_import :NSPortCoder
  ns_import :NSPortMessage
  ns_import :NSPortNameServer
  ns_import :NSMachBootstrapServer
  ns_import :NSMessagePortNameServer
  ns_import :NSSocketPortNameServer
  ns_import :NSProcessInfo
  ns_import :NSPropertyListSerialization
  ns_import :NSProtocolChecker
  ns_import :NSProxy
  ns_import :NSRunLoop
  ns_import :NSScriptClassDescription
  ns_import :NSScriptCoercionHandler
  ns_import :NSScriptCommand
  ns_import :NSScriptCommandDescription
  ns_import :NSScriptExecutionContext
  ns_import :NSScriptObjectSpecifier
  ns_import :NSIndexSpecifier
  ns_import :NSMiddleSpecifier
  ns_import :NSNameSpecifier
  ns_import :NSPositionalSpecifier
  ns_import :NSPropertySpecifier
  ns_import :NSRandomSpecifier
  ns_import :NSRangeSpecifier
  ns_import :NSRelativeSpecifier
  ns_import :NSUniqueIDSpecifier
  ns_import :NSWhoseSpecifier
  ns_import :NSCloneCommand
  ns_import :NSCloseCommand
  ns_import :NSCountCommand
  ns_import :NSCreateCommand
  ns_import :NSDeleteCommand
  ns_import :NSExistsCommand
  ns_import :NSGetCommand
  ns_import :NSMoveCommand
  ns_import :NSQuitCommand
  ns_import :NSSetCommand
  ns_import :NSScriptSuiteRegistry
  ns_import :NSScriptWhoseTest
  ns_import :NSLogicalTest
  ns_import :NSSpecifierTest
  ns_import :NSSerializer
  ns_import :NSDeserializer
  ns_import :NSSet
  ns_import :NSMutableSet
  ns_import :NSCountedSet
  ns_import :NSSpellServer
  ns_import :NSMutableString
  ns_import :NSSimpleCString
  ns_import :NSConstantString
  ns_import :NSTask
  ns_import :NSThread
  ns_import :NSTimer
  ns_import :NSTimeZone
  ns_import :NSUndoManager
  ns_import :NSURL
  ns_import :NSURLHandle
  ns_import :NSUserDefaults

end
