# -*- mode:ruby; indent-tabs-mode:nil; coding:utf-8 -*-

require 'rake_support'

# tasks
namespace :dep do
  load 'dependent/tasks.rake'
end

namespace :fw do

  desc "build RubyCocoa.framework"
  task :build => :build_release

  desc "build RubyCocoa.framework (Release)"
  task :build_release => [ 'dep:libffi:build' ] do
    chdir "framework" do
      xcodebuild "-configuration", "Release"
    end
  end

  desc "build RubyCocoa.framework (Debug)"
  task :build_debug => [ 'dep:libffi:build' ] do
    chdir "framework" do
      xcodebuild "-configuration", "Debug"
    end
  end

  desc "remove the framework/build"
  task :clean do
    chdir "framework" do
      xcodebuild "clean"
      rm_rf "build"
    end
  end
end
